package app.scheduler.utils;

public class SQLQueries {
    public static final String BATCHCOURSEMAPPING_FIND_BY_ID = "SELECT * FROM batch_course_mappings WHERE id = ?";
    public static final String BATCHCOURSEMAPPING_FIND_ALL = "SELECT * FROM batch_course_mappings";
    public static final String BATCHCOURSEMAPPING_DELETE = "DELETE FROM batch_course_mappings WHERE id = ?";
    public static final String BATCHCOURSEMAPPING_FIND_BY_BATCH_ID = "SELECT * FROM batch_course_mappings WHERE batch_id = ?";
    public static final String BATCHCOURSEMAPPING_FIND_BY_SEMESTER_ID = "SELECT * FROM batch_course_mappings WHERE semester_id = ?";
    public static final String BATCHCOURSEMAPPING_FIND_BY_BATCH_ID_AND_COURSE_ID = "SELECT * FROM batch_course_mappings WHERE batch_id = ? AND course_id = ?";
    public static final String BATCH_FIND_BY_ID = "SELECT * FROM batches WHERE id = ?";
    public static final String BATCH_FIND_ALL = "SELECT * FROM batches";
    public static final String BATCH_DELETE = "DELETE FROM batches WHERE id = ?";
    public static final String BATCH_FIND_BY_SEMESTER_ID = "SELECT * FROM batches WHERE semester_id = ?";
    public static final String BATCH_FIND_BY_PROGRAM = "SELECT * FROM batches WHERE program = ?";
    public static final String COURSE_FIND_BY_ID = "SELECT * FROM courses WHERE id = ?";
    public static final String COURSE_FIND_ALL = "SELECT * FROM courses";
    public static final String COURSE_DELETE = "DELETE FROM courses WHERE id = ?";
    public static final String EVENT_FIND_BY_ID = "SELECT * FROM events WHERE id = ?";
    public static final String EVENT_FIND_ALL = "SELECT * FROM events";
    public static final String EVENT_DELETE = "DELETE FROM events WHERE id = ?";
    public static final String EVENT_FIND_BY_SECTION_ID = "SELECT * FROM events WHERE section_id = ?";
    public static final String EVENT_FIND_BY_TEACHER_ID = "SELECT * FROM events WHERE teacher_id = ?";
    public static final String EVENT_FIND_BY_ROOM_ID = "SELECT * FROM events WHERE room_id = ?";
    public static final String EVENT_FIND_BY_SEMESTER_ID = "SELECT * FROM events WHERE semester_id = ?";
    public static final String EVENT_FIND_BY_SECTION_ID_AND_WEEK = "SELECT * FROM events WHERE section_id = ? AND week = ?";
    public static final String EVENT_FIND_BY_TEACHER_ID_AND_DAY = "SELECT * FROM events WHERE teacher_id = ? AND day = ?";
    public static final String ROOM_FIND_BY_ID = "SELECT * FROM rooms WHERE id = ?";
    public static final String ROOM_FIND_ALL = "SELECT * FROM rooms";
    public static final String ROOM_DELETE = "DELETE FROM rooms WHERE id = ?";
    public static final String SECTION_FIND_BY_ID = "SELECT * FROM sections WHERE id = ?";
    public static final String SECTION_FIND_ALL = "SELECT * FROM sections";
    public static final String SECTION_DELETE = "DELETE FROM sections WHERE id = ?";
    public static final String SECTION_FIND_BY_BATCH_ID = "SELECT * FROM sections WHERE batch_id = ?";
    public static final String SECTION_FIND_BY_SEMESTER_ID = "SELECT * FROM sections WHERE semester_id = ?";
    public static final String SEMESTER_FIND_BY_ID = "SELECT * FROM semesters WHERE id = ?";
    public static final String SEMESTER_FIND_ALL = "SELECT * FROM semesters";
    public static final String SEMESTER_DELETE = "DELETE FROM semesters WHERE id = ?";
    public static final String SEMESTER_FIND_BY_ACADEMIC_YEAR = "SELECT * FROM semesters WHERE academic_year = ?";
    public static final String SESSION_FIND_BY_ID = "SELECT * FROM sessions WHERE id = ?";
    public static final String SESSION_FIND_ALL = "SELECT * FROM sessions";
    public static final String SESSION_DELETE = "DELETE FROM sessions WHERE id = ?";
    public static final String SESSION_FIND_BY_TOKEN = "SELECT * FROM sessions WHERE token = ?";
    public static final String STUDENT_FIND_BY_ID = "SELECT * FROM students WHERE id = ?";
    public static final String STUDENT_FIND_ALL = "SELECT * FROM students";
    public static final String STUDENT_DELETE = "DELETE FROM students WHERE id = ?";
    public static final String TEACHER_FIND_BY_ID = "SELECT * FROM teachers WHERE id = ?";
    public static final String TEACHER_FIND_ALL = "SELECT * FROM teachers";
    public static final String TEACHER_DELETE = "DELETE FROM teachers WHERE id = ?";
    public static final String USER_FIND_BY_ID = "SELECT * FROM users WHERE id = ?";
    public static final String USER_FIND_ALL = "SELECT * FROM users";
    public static final String USER_DELETE = "DELETE FROM users WHERE id = ?";
    public static final String USER_FIND_BY_USERNAME = "SELECT * FROM users WHERE username = ?";
}
