spring.application.name=scheduler

# 1. Tell Spring Boot where your SQLite database file lives
# spring.datasource.url=jdbc:sqlite:database/database.db
spring.datasource.url=jdbc:sqlite:database/database.db
spring.datasource.driver-class-name=org.sqlite.JDBC


# 2. Provide the modern Hibernate community dialect for SQLite
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect


# 3. Disable Hibernate auto DDL, use custom schema.sql
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:db/schema.sql



# Turn off the giant ASCII "Spring" logo on startup
# spring.main.banner-mode=off


# Set the root logger to WARN (hides INFO/DEBUG logs framework-wide)
logging.level.root=WARN


# Keep your own code's packages loud and clear (Change to your actual package path)
logging.level.com.example.demo=INFO


spring.devtools.restart.additional-paths=bin/main/,out/production/,build/classes/java/main/

