spring.application.name=scheduler

# 1. Tell Spring Boot where your SQLite database file lives
# spring.datasource.url=jdbc:sqlite:database/database.db
spring.datasource.url=jdbc:sqlite:database/database.db
spring.datasource.driver-class-name=org.sqlite.JDBC


# 2. Provide the modern Hibernate community dialect for SQLite
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect


# 3. Disable Hibernate auto DDL, use custom schema.sql
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:db/schema.sql



# Set the root logger to ERROR to hide verbose framework logs
logging.level.root=ERROR
logging.level.org.springframework=ERROR
logging.level.org.hibernate=ERROR
logging.level.com.zaxxer=ERROR
logging.level.app.scheduler=INFO

# Turn off the Spring Boot banner
spring.main.banner-mode=off

spring.devtools.restart.additional-paths=bin/main/,out/production/,build/classes/java/main/

