spring.application.name=scheduler

spring.datasource.url=jdbc:sqlite:database/database.db
spring.datasource.driver-class-name=org.sqlite.JDBC


spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect


spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:db/schema.sql



logging.level.root=ERROR
logging.level.org.springframework=ERROR
logging.level.org.hibernate=ERROR
logging.level.com.zaxxer=ERROR
logging.level.app.scheduler=INFO

spring.main.banner-mode=off

spring.devtools.restart.additional-paths=bin/main/,out/production/,build/classes/java/main/

